/**
 *
 * @file SCB_Enum.h
 * @copyright
 * @verbatim InDeviceMex 2020 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 19 jun. 2020 @endverbatim
 *
 * @author
 * @verbatim vyldram @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 19 jun. 2020     vyldram    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_
#define XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_

#include <xDriver_MCU/Common/xHeader/MCU_Enum.h>

#define SCB_VECTOR_TABLE_SIZE ((UBase_t) 0x00000100UL)

typedef enum
{
    SCB_enERROR_OK = (UBase_t) MCU_enERROR_OK,
    SCB_enERROR_POINTER = (UBase_t) MCU_enERROR_POINTER,
    SCB_enERROR_VALUE = (UBase_t) MCU_enERROR_VALUE,
    SCB_enERROR_RANGE = (UBase_t) MCU_enERROR_RANGE,
    SCB_enERROR_UNDEF = (UBase_t) MCU_enERROR_UNDEF,
}SCB_nERROR;

typedef enum
{
    SCB_enPRI0 = (UBase_t) MCU_enPRI0,
    SCB_enPRI1 = (UBase_t) MCU_enPRI1,
    SCB_enPRI2 = (UBase_t) MCU_enPRI2,
    SCB_enPRI3 = (UBase_t) MCU_enPRI3,
    SCB_enPRI4 = (UBase_t) MCU_enPRI4,
    SCB_enPRI5 = (UBase_t) MCU_enPRI5,
    SCB_enPRI6 = (UBase_t) MCU_enPRI6,
    SCB_enPRI7 = (UBase_t) MCU_enPRI7,
    SCB_enPRIMAX = (UBase_t) MCU_enPRIMAX,
    SCB_enDEFAULT = (UBase_t) MCU_enDEFAULT,
}SCB_nPRIORITY;


typedef enum
{
    SCB_enSTATE_DIS = (UBase_t) MCU_enSTATE_DIS,
    SCB_enSTATE_ENA = (UBase_t) MCU_enSTATE_ENA,
    SCB_enSTATE_UNDEF = UNDEF_VALUE,
}SCB_nSTATE;

typedef enum
{
    SCB_enMODULE_0 = 0UL,
    SCB_enMODULE_MAX = 1UL,
    SCB_enMODULE_UNDEF = UNDEF_VALUE,
}SCB_nMODULE;

typedef enum
{
    SCB_enPRIGROUP_XXX = 4UL,
    SCB_enPRIGROUP_XXY = 5UL,
    SCB_enPRIGROUP_XYY = 6UL,
    SCB_enPRIGROUP_YYY = 7UL,
    SCB_enPRIGROUP_MAX = 8UL,
    SCB_enPRIGROUP_ERROR = UNDEF_VALUE,
}SCB_nPRIGROUP;

typedef enum
{
    SCB_enNOPENDING = 0UL,
    SCB_enPENDING = 1UL,
    SCB_enPENDSTATE_UNDEF = UNDEF_VALUE,
}SCB_nPENDSTATE;

typedef enum
{
    SCB_enFAULT_USAGE = 0UL,
    SCB_enFAULT_BUS = 1UL,
    SCB_enFAULT_MEMORY = 2UL,
    SCB_enFAULT_HARD = 3UL,
    SCB_enFAULT_NMI = 4UL,
    SCB_enFAULT_MAX = 5UL,
    SCB_enFAULT_UNDEF = UNDEF_VALUE,
}SCB_nFAULT;

typedef enum
{
    SCB_enNMI_NONE = 0x00UL,
    SCB_enNMI_EXTERNAL = 0x01UL,
    SCB_enNMI_POWER = 0x04UL,
    SCB_enNMI_WDT0 = 0x08UL,
    SCB_enNMI_WDT1 = 0x20UL,
    SCB_enNMI_TAMPER = 0x200UL,
    SCB_enNMI_MOSC_FAILURE = 0x10000UL,
    SCB_enNMI_ALL = 0x1022DUL,
    SCB_enNMI_UNDEF = UNDEF_VALUE,
}SCB_nNMI;

typedef enum
{
    SCB_enNMI_BIT_EXTERNAL = 0UL,
    SCB_enNMI_BIT_POWER = 1UL,
    SCB_enNMI_BIT_WDT0 = 2UL,
    SCB_enNMI_BIT_WDT1 = 3UL,
    SCB_enNMI_BIT_TAMPER = 4UL,
    SCB_enNMI_BIT_MOSC_FAILURE = 5UL,
    SCB_enNMI_BIT_SW = 6UL,
    SCB_enNMI_BIT_MAX = 7UL,
    SCB_enNMI_BIT_UNDEF = UNDEF_VALUE,
}SCB_nNMI_BIT;

typedef enum
{
    SCB_enHARD_NONE = 0x00UL,
    SCB_enHARD_VECT = 0x02UL,
    SCB_enHARD_ALL = 0x02UL,
    SCB_enHARD_UNDEF = UNDEF_VALUE,
}SCB_nHARD;

typedef enum
{
    SCB_enHARD_BIT_VECT = 0UL,
    SCB_enHARD_BIT_SW = 1UL,
    SCB_enHARD_BIT_MAX = 2UL,
    SCB_enHARD_BIT_UNDEF = UNDEF_VALUE,
}SCB_nHARD_BIT;

typedef enum
{
    SCB_enUSAGE_NONE = 0x0000UL,
    SCB_enUSAGE_UNDEFINSTR = 0x0001UL,
    SCB_enUSAGE_INVSTATE = 0x0002UL,
    SCB_enUSAGE_INVPC = 0x0004UL,
    SCB_enUSAGE_NOCP = 0x0008UL,
    SCB_enUSAGE_UNALIGNED = 0x0100UL,
    SCB_enUSAGE_DIVBYZERO = 0x0200UL,
    SCB_enUSAGE_ALL = 0x030FUL,
    SCB_enUSAGE_UNDEF = UNDEF_VALUE,
}SCB_nUSAGE;

typedef enum
{
    SCB_enUSAGE_BIT_UNDEFINSTR = 0UL,
    SCB_enUSAGE_BIT_INVSTATE = 1UL,
    SCB_enUSAGE_BIT_INVPC = 2UL,
    SCB_enUSAGE_BIT_NOCP = 3UL,
    SCB_enUSAGE_BIT_UNALIGNED = 4UL,
    SCB_enUSAGE_BIT_DIVBYZERO = 5UL,
    SCB_enUSAGE_BIT_SW = 6UL,
    SCB_enUSAGE_BIT_MAX = 7UL,
    SCB_enUSAGE_BIT_UNDEF = UNDEF_VALUE,
}SCB_nUSAGE_BIT;

typedef enum
{
    SCB_enBUS_NONE = 0x00UL,
    SCB_enBUS_IBUSERR = 0x01UL,
    SCB_enBUS_PRECISERR = 0x02UL,
    SCB_enBUS_IMPRECISERR = 0x04UL,
    SCB_enBUS_UNSTKERR = 0x08UL,
    SCB_enBUS_STKERR = 0x10UL,
    SCB_enBUS_LSPERR = 0x20UL,
    SCB_enBUS_BFARVALID = 0x80UL,
    SCB_enBUS_ALL = 0xBFUL,
    SCB_enBUS_UNDEF = UNDEF_VALUE,
}SCB_nBUS;

typedef enum
{
    SCB_enBUS_BIT_IBUSERR = 0UL,
    SCB_enBUS_BIT_PRECISERR = 1UL,
    SCB_enBUS_BIT_IMPRECISERR = 2UL,
    SCB_enBUS_BIT_UNSTKERR = 3UL,
    SCB_enBUS_BIT_STKERR = 4UL,
    SCB_enBUS_BIT_LSPERR = 5UL,
    SCB_enBUS_BIT_BFARVALID = 6UL,
    SCB_enBUS_BIT_SW = 7UL,
    SCB_enBUS_BIT_MAX = 8UL,
    SCB_enBUS_BIT_UNDEF = UNDEF_VALUE,
}SCB_nBUS_BIT;

typedef enum
{
    SCB_enMEMORY_NONE = 0x00UL,
    SCB_enMEMORY_IACCVIOL = 0x01UL,
    SCB_enMEMORY_DACCVIOL = 0x02UL,
    SCB_enMEMORY_MUNSTKERR = 0x08UL,
    SCB_enMEMORY_MSTKERR = 0x10UL,
    SCB_enMEMORY_MLSPERR = 0x20UL,
    SCB_enMEMORY_MMARVALID = 0x80UL,
    SCB_enMEMORY_ALL = 0xBBUL,
    SCB_enMEMORY_UNDEF = UNDEF_VALUE,
}SCB_nMEMORY;

typedef enum
{
    SCB_enMEMORY_BIT_IACCVIOL = 0UL,
    SCB_enMEMORY_BIT_DACCVIOL = 1UL,
    SCB_enMEMORY_BIT_MUNSTKERR = 2UL,
    SCB_enMEMORY_BIT_MSTKERR = 3UL,
    SCB_enMEMORY_BIT_MLSPERR = 4UL,
    SCB_enMEMORY_BIT_MMARVALID = 5UL,
    SCB_enMEMORY_BIT_SW = 6UL,
    SCB_enMEMORY_BIT_MAX = 7UL,
    SCB_enMEMORY_BIT_UNDEF = UNDEF_VALUE,
}SCB_nMEMORY_BIT;

typedef enum
{
    SCB_enALIGN_4BYTE = 0UL,
    SCB_enALIGN_8BYTE = 1UL,
    SCB_enALIGN_ERROR = UNDEF_VALUE,
}SCB_nALIGN;

typedef enum
{
    SCB_enWAKEUP_ONLY = 0UL,
    SCB_enWAKEUP_ALL = 1UL,
    SCB_enWAKEUP_UNDEF = UNDEF_VALUE,
}SCB_nWAKEUP;

typedef enum
{
    SCB_enSLEEPONEXIT_NOSLEEP = 0UL,
    SCB_enSLEEPONEXIT_SLEEP = 1UL,
    SCB_enSLEEPONEXIT_UNDEF = UNDEF_VALUE,
}SCB_nSLEEPONEXIT;

typedef enum
{
    SCB_enSLEEPMODE_SLEEP = 0UL,
    SCB_enSLEEPMODE_DEEPSLEEP = 1UL,
    SCB_enSLEEPMODE_UNDEF = UNDEF_VALUE,
}SCB_nSLEEPMODE;

typedef enum
{
    SCB_enVECISR_THREAD = 0UL,
    SCB_enVECISR_RESET = 1UL,
    SCB_enVECISR_NMI = 2UL,
    SCB_enVECISR_HARDFAULT = 3UL,
    SCB_enVECISR_MEMMANAGE = 4UL,
    SCB_enVECISR_BUSFAULT = 5UL,
    SCB_enVECISR_USAGEFAULT = 6UL,
    SCB_enVECISR_RES7 = 7UL,
    SCB_enVECISR_RES8 = 8UL,
    SCB_enVECISR_RES9 = 9UL,
    SCB_enVECISR_RES10 = 10UL,
    SCB_enVECISR_SVCALL = 11UL,
    SCB_enVECISR_DEBUGMON = 12UL,
    SCB_enVECISR_RES13 = 13UL,
    SCB_enVECISR_PENDSV = 14UL,
    SCB_enVECISR_SYSTICK = 15UL,
    SCB_enVECISR_GPIOA = 0UL + 16UL,
    SCB_enVECISR_GPIOB = 1UL + 16UL,
    SCB_enVECISR_GPIOC = 2UL + 16UL,
    SCB_enVECISR_GPIOD = 3UL + 16UL,
    SCB_enVECISR_GPIOE = 4UL + 16UL,
    SCB_enVECISR_UART0 = 5UL + 16UL,
    SCB_enVECISR_UART1 = 6UL + 16UL,
    SCB_enVECISR_SSI0 = 7UL + 16UL,
    SCB_enVECISR_I2C0 = 8UL + 16UL,
    SCB_enVECISR_PWM0FAULT = 9UL + 16UL,
    SCB_enVECISR_PWM0GEN0 = 10UL + 16UL,
    SCB_enVECISR_PWM0GEN1 = 11UL + 16UL,
    SCB_enVECISR_PWM0GEN2 = 12UL + 16UL,
    SCB_enVECISR_QEI0 = 13UL + 16UL,
    SCB_enVECISR_ADC0SEQ0 = 14UL + 16UL,
    SCB_enVECISR_ADC0SEQ1 = 15UL + 16UL,
    SCB_enVECISR_ADC0SEQ2 = 16UL + 16UL,
    SCB_enVECISR_ADC0SEQ3 = 17UL + 16UL,
    SCB_enVECISR_WDT01 = 18UL + 16UL,
    SCB_enVECISR_TIMER0A = 19UL + 16UL,
    SCB_enVECISR_TIMER0B = 20UL + 16UL,
    SCB_enVECISR_TIMER1A = 21UL + 16UL,
    SCB_enVECISR_TIMER1B = 22UL + 16UL,
    SCB_enVECISR_TIMER2A = 23UL + 16UL,
    SCB_enVECISR_TIMER2B = 24UL + 16UL,
    SCB_enVECISR_ACMP0 = 25UL + 16UL,
    SCB_enVECISR_ACMP1 = 26UL + 16UL,
    SCB_enVECISR_ACMP2 = 27UL + 16UL,
    SCB_enVECISR_SYSCTL = 28UL + 16UL,
    SCB_enVECISR_FLASH = 29UL + 16UL,
    SCB_enVECISR_GPIOF = 30UL + 16UL,
    SCB_enVECISR_GPIOG = 31UL + 16UL,
    SCB_enVECISR_GPIOH = 32UL + 16UL,
    SCB_enVECISR_UART2 = 33UL + 16UL,
    SCB_enVECISR_SSI1 = 34UL + 16UL,
    SCB_enVECISR_TIMER3A = 35UL + 16UL,
    SCB_enVECISR_TIMER3B = 36UL + 16UL,
    SCB_enVECISR_I2C1 = 37UL + 16UL,
    SCB_enVECISR_CAN0 = 38UL + 16UL,
    SCB_enVECISR_CAN1 = 39UL + 16UL,
    SCB_enVECISR_ETH = 40UL + 16UL,
    SCB_enVECISR_HIB = 41UL + 16UL,
    SCB_enVECISR_USB = 42UL + 16UL,
    SCB_enVECISR_PWM0GEN3 = 43UL + 16UL,
    SCB_enVECISR_UDMASOFT = 44UL + 16UL,
    SCB_enVECISR_UDMAERROR = 45UL + 16UL,
    SCB_enVECISR_ADC1SEQ0 = 46UL + 16UL,
    SCB_enVECISR_ADC1SEQ1 = 47UL + 16UL,
    SCB_enVECISR_ADC1SEQ2 = 48UL + 16UL,
    SCB_enVECISR_ADC1SEQ3 = 49UL + 16UL,
    SCB_enVECISR_EPI0 = 50UL + 16UL,
    SCB_enVECISR_GPIOJ = 51UL + 16UL,
    SCB_enVECISR_GPIOK = 52UL + 16UL,
    SCB_enVECISR_GPIOL = 53UL + 16UL,
    SCB_enVECISR_SSI2 = 54UL + 16UL,
    SCB_enVECISR_SSI3 = 55UL + 16UL,
    SCB_enVECISR_UART3 = 56UL + 16UL,
    SCB_enVECISR_UART4 = 57UL + 16UL,
    SCB_enVECISR_UART5 = 58UL + 16UL,
    SCB_enVECISR_UART6 = 59UL + 16UL,
    SCB_enVECISR_UART7 = 60UL + 16UL,
    SCB_enVECISR_I2C2 = 61UL + 16UL,
    SCB_enVECISR_I2C3 = 62UL + 16UL,
    SCB_enVECISR_TIMER4A = 63UL + 16UL,
    SCB_enVECISR_TIMER4B = 64UL + 16UL,
    SCB_enVECISR_TIMER5A = 65UL + 16UL,
    SCB_enVECISR_TIMER5B = 66UL + 16UL,
    SCB_enVECISR_SYSEXC = 67UL + 16UL,
    SCB_enVECISR_RES84 = 68UL + 16UL,
    SCB_enVECISR_RES85 = 69UL + 16UL,
    SCB_enVECISR_I2C4 = 70UL + 16UL,
    SCB_enVECISR_I2C5 = 71UL + 16UL,
    SCB_enVECISR_GPIOM = 72UL + 16UL,
    SCB_enVECISR_GPION = 73UL + 16UL,
    SCB_enVECISR_RES90 = 74UL + 16UL,
    SCB_enVECISR_TAMPER = 75UL + 16UL,
    SCB_enVECISR_GPIOP = 76UL + 16UL,
    SCB_enVECISR_GPIOP1 = 77UL + 16UL,
    SCB_enVECISR_GPIOP2 = 78UL + 16UL,
    SCB_enVECISR_GPIOP3 = 79UL + 16UL,
    SCB_enVECISR_GPIOP4 = 80UL + 16UL,
    SCB_enVECISR_GPIOP5 = 81UL + 16UL,
    SCB_enVECISR_GPIOP6 = 82UL + 16UL,
    SCB_enVECISR_GPIOP7 = 83UL + 16UL,
    SCB_enVECISR_GPIOQ = 84UL + 16UL,
    SCB_enVECISR_GPIOQ1 = 85UL + 16UL,
    SCB_enVECISR_GPIOQ2 = 86UL + 16UL,
    SCB_enVECISR_GPIOQ3 = 87UL + 16UL,
    SCB_enVECISR_GPIOQ4 = 88UL + 16UL,
    SCB_enVECISR_GPIOQ5 = 89UL + 16UL,
    SCB_enVECISR_GPIOQ6 = 90UL + 16UL,
    SCB_enVECISR_GPIOQ7 = 91UL + 16UL,
    SCB_enVECISR_GPIOR = 92UL + 16UL,
    SCB_enVECISR_GPIOS = 93UL + 16UL,
    SCB_enVECISR_SHA_MD5 = 94UL + 16UL,
    SCB_enVECISR_AES = 95UL + 16UL,
    SCB_enVECISR_DES = 96UL + 16UL,
    SCB_enVECISR_LCD = 97UL + 16UL,
    SCB_enVECISR_TIMER6A = 98UL + 16UL,
    SCB_enVECISR_TIMER6B = 99UL + 16UL,
    SCB_enVECISR_TIMER7A = 100UL + 16UL,
    SCB_enVECISR_TIMER7B = 101UL + 16UL,
    SCB_enVECISR_I2C6 = 102UL + 16UL,
    SCB_enVECISR_I2C7 = 103UL + 16UL,
    SCB_enVECISR_KEYBOARD = 104UL + 16UL,
    SCB_enVECISR_ONEWIRE = 105UL + 16UL,
    SCB_enVECISR_PS2 = 106UL + 16UL,
    SCB_enVECISR_LEDSEQ = 107UL + 16UL,
    SCB_enVECISR_IR = 108UL + 16UL,
    SCB_enVECISR_I2C8 = 109UL + 16UL,
    SCB_enVECISR_I2C9 = 110UL + 16UL,
    SCB_enVECISR_GPIOT = 111UL + 16UL,
    SCB_enVECISR_FAN = 112UL + 16UL,
    SCB_enVECISR_RES129 = 113UL + 16UL,
    SCB_enVECISR_MAX = 114UL + 16UL,
    SCB_enVECISR_UNDEF = UNDEF_VALUE,
}SCB_nVECISR;

typedef MCU_Register_t SCB_Register_t;
typedef MCU_pvfIRQVectorHandler_t SCB_pvfIRQVectorHandler_t;
typedef MCU_pvfIRQSourceHandler_t SCB_pvfIRQSourceHandler_t;

#endif /* XDRIVER_MCU_DRIVER_HEADER_SCB_SCB_PERIPHERAL_SCB_ENUM_H_ */
