add_subdirectory(ACMP)
add_subdirectory(ADC/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(DMA/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(EEPROM/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(FLASH/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(GPIO/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(HIB/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(I2C/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(PWM/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(QEI/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(SSI/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(SYSEXC)
add_subdirectory(Core)
add_subdirectory(SYSCTL)
add_subdirectory(UART/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)
add_subdirectory(WDT/Driver/Intrinsics/Interrupt/InterruptRoutine/xSource)